### ISSUE TITLE
Zsh segfault

### ISSUE THREAD

**Issue by yuyichao** [Keno/anubis.juliacomputing.io#1]
@Keno 

Similar to https://bugs.alpinelinux.org/issues/5699 although the `.zshrc` to reproduce it (below) is slightly longer. With the following `.zshrc` typing `l<enter>` makes zsh segfault.

``` sh
__yyc_zle_init_func_handlers=()

__yyc_zle_init_func() {
    unset __yyc_zle_init_func_handlers
    zle -D zle-line-init
}

zle -N __yyc_zle_init_func
zle -A __yyc_zle_init_func zle-line-init
zle -D __yyc_zle_init_func
```

**Comment by Keno** [comment]
Shall I install a more recent zsh from source?

**Comment by yuyichao** [comment]
Assuming it's the same bug, it seems to be fixed right after the latest version (5.2, released on Dec. 2nd, 2015, also the installed version) is released on Dec. 7th, 2015 https://github.com/zsh-users/zsh/commit/0c2d823a7955981e88f7cb5b718a7081d97104f0 so maybe the same version with patch...

**Comment by Keno** [comment]
zsh 5.2 with that patch is now installed as `/usr/local/bin/zsh`.

**Comment by yuyichao** [comment]
Confirmed that my full `.zshrc` doesn't segfault anymore.
