### ISSUE TITLE
Allow limiting resources of user processes with cgroups

### ISSUE THREAD

**Issue by yuyichao** [Keno/anubis.juliacomputing.io#2]
The use case is that I want to have some tests running continuously and I want to put a hard limit on some resources it uses (mostly CPU) as well as changing it dynamically/automatically (e.g. to use less CPU during the day or when someone else is also using it).

The closest I've found is cgroups but it seems that the bare API requires root privilege by default and systemd does not currently provide this function for user units either. I've also tried user namespace but it doesn't seem to help.

It seems that one way to do this is to create a subgroup in the corresponding cgroup file systemd with the user as owner. i.e.

``` sh
# mkdir /sys/fs/cgroup/cpuset/<uid>
# chown -R <uid>:<gid> /sys/fs/cgroup/cpuset/<uid>
```

The user can now create subgroups in the new `<uid>` group and put process (trees) into the subgroup to limit the cpu resources used by the process.

For now, I think I mainly want the `cpuset` cgroup or `cpu,cpuacct` cgroup (not exactly sure the difference yet). The `freezer` cgroup might be useful to temporarily pause the processes completely too.

Given that this is not enabled by default there's probably some detail that I'm not seeing but it seems that this shouldn't give the user to limit the resources of arbitrary processes (only the users own or the ones started by the user).

**Comment by yuyichao** [comment]
@Keno

**Comment by Keno** [comment]
I did 

`sudo cgcreate -t yuyichao:yuyichao -a yuyichao:yuyichao -g cpuset:/yuyichaos-cgroup`

Let me know if that does what you need.

**Comment by yuyichao** [comment]
After reading/trying more locally I think `cpu,cpuacct`might be slightly better but let me give it a try first. Thanks.
